const i18Obj = {
    en: {
      skills: "Skills",
      portfolio: "Portfolio",
      video: "Video",
      price: "Price",
      contacts: "Contacts",
      "hero-title": "Alexa Rise",
      "hero-text":
        "Save sincere emotions, romantic feelings and happy moments of life together with professional photographer Alexa Rise",
      hire: "Hire me",
      "skill-title-1": "Digital photography",
      "skill-text-1": "High-quality photos in the studio and on the nature",
      "skill-title-2": "Video shooting",
      "skill-text-2": "Capture your moments so that they always stay with you",
      "skill-title-3": "Rotouch",
      "skill-text-3": "I strive to make photography surpass reality",
      "skill-title-4": "Audio",
      "skill-text-4":
        "Professional sounds recording for video, advertising, portfolio",
      zima: "Winter",
      spring: "Spring",
      summer: "Summer",
      autumn: "Autumn",
      'standart':'Standart',
      'premium':'Premium',
      'gold':'Gold',
      'order shooting': 'Order shooting',
      "price-description-1-li-1": "One location, 120 photos in color, 12 photos in retouch, Readiness 2-3 weeks, Make up, visage", 
      "price-description-2-li-1": "One or two locations, 200 photos in color, 20 photos in retouch, Readiness 1-2 weeks,Make up, visage",
      "price-description-3-li-1": "Three locations or more, 300 photos in color, 50 photos in retouch, Readiness 1 week, Make up, visage, hairstyle",
      order: "Order shooting",
      "contact-me": "Contact me",
      "send-message": "Send message",
    },
    ru: {
      skills: "Навыки",
      portfolio: "Портфолио",
      video: "Видео",
      price: "Цены",
      contacts: "Контакты",
      "hero-title": "Алекса Райс",
      "hero-text":
        "Сохраните искренние эмоции, романтические переживания и счастливые моменты жизни вместе с профессиональным фотографом",
      hire: "Пригласить",
      "skill-title-1": "Фотография",
      "skill-text-1": "Высококачественные фото в студии и на природе",
      "skill-title-2": "Видеосъемка",
      "skill-text-2":
        "Запечатлите лучшие моменты, чтобы они всегда оставались с вами",
      "skill-title-3": "Ретушь",
      "skill-text-3":
        "Я стремлюсь к тому, чтобы фотография превосходила реальность",
      "skill-title-4": "Звук",
      "skill-text-4":
        "Профессиональная запись звука для видео, рекламы, портфолио",
      zima: "Зима",
      spring: "Весна",
      summer: "Лето",
      autumn: "Осень",
      'standart':'Стандарт',
      'premium':'Премиум',
      'gold':'Голд',
      'order shooting': 'Заказать съемку',
      "price-description-1-li-1": "Одна локация, 120 цветных фото, 12 отретушированных фото, Готовность через 2-3 недели, Макияж, визаж",
      "price-description-2-li-1": "Одна-две локации, 200 цветных фото, 20 отретушированных фото, Готовность через 1-2 недели, Макияж, визаж",
      "price-description-3-li-1": "Три локации и больше, 300 цветных фото, 50 отретушированных фото, Готовность через 1 неделю, Макияж, визаж, прическа",
      order: "Заказать съемку",
      "contact-me": "Свяжитесь со мной",
      "send-message": "Отправить",
    },
  };
  export default i18Obj;
